# Generated by Django 6.0 on 2025-12-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('CRYPTO', 'Kripto Para'), ('GOLD', 'Altın/Emtia'), ('STOCK', 'Borsa (BIST)')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('daily_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('long_term_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finansal Veri',
                'verbose_name_plural': 'Finansal Veriler',
            },
        ),
    ]
