# Generated by Django 6.0 on 2025-12-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='daily_change_percent',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='long_term_change_percent',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='change_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='change_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='change_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='change_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='chart_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='data_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
